#11-modul. Maʼlumotlarga ishlov berish. Maʼlumotlarni tayyorlash
# 11.28. Modul boʻyicha yakuniy amaliy vazifa

**Bu vazifalarni bajargach, maʼlumotlarni yuklash, tozalash, oʻzgartirish, matnlarni normalizatsiya qilish, qiymatlarni tekshirish, guruhlash va tahlil qilish kabi maʼlumotlarga ishlov berish (data processing) koʻnikmalarini egallaysiz.**

#**Umumiy maʼlumotlar bilan ishlash**

#Dataset haqida qisqacha maʼlumot
Restoran savdosi boʻyicha maʼlumotlar toʻplami 17 534 tranzaksiya uchun maʼlumotlarni oʻz ichiga oladi. Maʼlumotlar yetishmayotgan yoki baʼzilari toʻliq kiritilmagan boʻlishi mumkin. Maʼlumotlar toʻplamida asosiy taomlar, shirinliklar, ichimliklar kabi bir nechta toifadagi savdo tafsilotlari mavjud.


 0.   **Unnamed 0** – indekslarni;
 1.   **Order ID** – buyurtma IDʼsini;
 2.   **Customer ID** – mijoz IDʼsini;
 3.   **Category** – mahsulotlar kategoriyasini;
 4.   **Item** – mahsulot nomini;
 5.   **Price** – mahsulotning narxini;
 6.   **Quantity** – qancha mahsulot sotilgani miqdorini;
 7.   **Order Total** – umumiy narx qancha ekanini;
 8.   **Order Date** – buyurtma berilgan sanani (vaqt);
 9.   **Payment Method** – toʻlov usuli turini saqlaydi.

#1) Quyida berilgan datasetni yuklab olib, ustun nomlarini koʻring va ularni maʼno jihatdan tushunarli shaklga keltiring. `Unnamed: 0` ustunini tashlab yuboring!

In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/restaurant_sales.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [ ]:
#javobni shu yerda yozing
df.drop(columns=['Unnamed: 0'], inplace=True)

df.rename(columns = {
    'Order ID'       : 'order_id',
    'Customer ID'    : 'customer_id',
    'Category'       : 'category',
    'Item'           : 'item',
    'Price'          : 'price',
    'Quantity'       : 'quantity',
    'Order Total'    : 'order_total',
    'Order Date'     : 'order_date',
    'Payment Method' : 'payment_method'
}, inplace =True)

df.head()

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

#2) Maʼlumotlarning umumiy holatini (info(), describe()) tekshiring.

In [ ]:
#javobni shu yerda yozing
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        17534 non-null  object
 1   customer_id     17534 non-null  object
 2   category        17498 non-null  object
 3   item            15776 non-null  object
 4   price           17534 non-null  float64
 5   quantity        17104 non-null  float64
 6   order_total     17104 non-null  float64
 7   order_date      17534 non-null  object
 8   payment_method  16452 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB
None
              price      quantity   order_total
count  17534.000000  17104.000000  17104.000000
mean       6.207312      3.014149     19.914494
std        4.993782      1.414598     18.732549
min       -1.000000      1.000000      1.000000
25%        3.000000      2.000000      7.500000
50%        5.000000      3.000000     15.000000
75%        7.000000      4.000000     25.000000
max       20.000000      5.000000    100.000000

#3) Har bir ustundagi boʻsh qiymatlarni aniqlang va ularni toʻldirish strategiyasini ishlab chiqing.

In [ ]:
#javobni shu yerda yozing

df1 = df.dropna(subset = ['category', 'item', 'quantity', 'order_total']).copy()
df1['payment_method'] = df1['payment_method'].fillna(df1['payment_method'].mode()[0])

#df1.isnull().sum() # checking if there is any NaN value left
df1.head()

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5.0,90.0,2022-07-20,Digital Wallet
6,ORD_270994,CUST_071,Side Dishes,Garlic Bread,4.0,5.0,20.0,2022-08-19,Credit Card

#4) Har bir ustundagi takroriy qiymatlarni toping va ularga qanday oʻzgartirish kiritish kerakligini hal qiling.

In [ ]:
#javobni shu yerda yozing
df1.duplicated().sum()  # there is no any duplicated values

np.int64(0)

#5) Maʼlumotlar toʻplamidagi noto‘g‘ri maʼlumotlar (masalan, son turishi kerak bo‘lgan ustunda matn bo‘lsa) mavjudligini tekshiring va to‘g‘rilang.

In [ ]:
df1[df1.price < 0]

Empty DataFrame
Columns: [order_id, customer_id, category, item, price, quantity, order_total, order_date, payment_method]
Index: []

In [ ]:
#javobni shu yerda yozing
# df1.info()
import datetime as dt

df1['order_date'] = pd.to_datetime(df1['order_date'])
df1['quantity'] = df1['quantity'].astype(int)
df1['order_total'] = df1['order_total'].astype(int)
df1.head()

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3,12,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4,60,2023-09-27,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4,48,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5,90,2022-07-20,Digital Wallet
6,ORD_270994,CUST_071,Side Dishes,Garlic Bread,4.0,5,20,2022-08-19,Credit Card

In [ ]:
df1.dtypes

order_id                  object
customer_id               object
category                  object
item                      object
price                    float64
quantity                   int64
order_total                int64
order_date        datetime64[ns]
payment_method            object
dtype: object

#6) Maʼlumotlar toʻplamidagi **katta/kichik harf** muammolari boʻlgan joylarni toping va bir xil formatga keltiring.

In [ ]:
print(df1['category'].unique())
print(df1['item'].unique())
print(df1['payment_method'].unique())

['Side Dishes' 'Main Dishes' 'Desserts' 'Starters' 'Drinks']
['Mashed Potatoes' 'Grilled Chicken' 'Pasta Alfredo' 'Salmon'
 'Garlic Bread' 'Vegetarian Platter' 'Brownie' 'Sweet Potato Fries'
 'Lemonade' 'Side Salad' 'Orange Juice' 'Chocolate Cake' 'COCA COLA'
 'Grilled Vegetables' 'Coca Cola' 'Cheese Fries' 'Beef Chili'
 'Chicken Melt' 'Fruit Salad' 'French Fries' 'Ice Cream' 'Cheesecake'
 'CHOCOLATE CAKE' 'grilled vegetables' 'Iced Tea' 'Water (0.5)'
 'Grilled Vegetables?' 'NACHOS GRANDE#' 'water' 'Onion Rings' 'STEAK'
 'Steak' 'LEMONADE' 'Nachos Grande' 'Grilled Chicken?' 'ICED TEA'
 'CHICKEN MELT#' 'lemonade (1.0)' 'ICE CREAM' 'GRILLED CHICKEN'
 'french fries' 'GRILLED CHICKEN#' 'grilled chicken' 'Coca Cola?'
 'FRUIT SALAD' 'steak' 'STEAK#' 'COCA COLA?' 'fruit salad'
 'MASHED POTATOES' 'cheesecake' 'French Fries?' 'CHEESE FRIES'
 'Side Salad?' 'FRENCH FRIES#' 'SWEET POTATO FRIES' 'PASTA ALFREDO'
 'onion rings' 'Nachos Grande?' 'BROWNIE#' 'ice cream'
 'GRILLED VEGETABLES' 'coca cola' 'CHOCOLATE CAKE#' 'ORANGE JUICE'
 'PASTA ALFREDO#' 'chicken melt?' 'chocolate cake' 'Sweet Potato Fries?'
 'BEEF CHILI' 'french fries#' 'Iced Tea?' 'sweet potato fries'
 'Vegetarian Platter?' 'WATER#' 'SIDE SALAD' 'pasta alfredo'
 'CHEESE FRIES?' 'GRILLED VEGETABLES#' 'iced tea' 'FRENCH FRIES'
 'Cheese Fries?' 'mashed potatoes' 'BEEF CHILI#' 'GARLIC BREAD'
 'Mashed Potatoes?' 'VEGETARIAN PLATTER' 'Orange Juice?'
 'vegetarian platter' 'ICED TEA#?' 'garlic bread' 'Pasta Alfredo?'
 'COCA COLA#' 'side salad' 'fruit salad?' 'Brownie?' 'STEAK?'
 'Beef Chili?' 'CHICKEN MELT' 'Water?' 'CHEESE FRIES#' 'BROWNIE' 'WATER'
 'Lemonade?' 'ICE CREAM#' 'SALMON' 'Steak?' 'orange juice' 'CHEESECAKE?'
 'beef chili' 'Chocolate Cake?' 'Chicken Melt?' 'brownie' 'ice cream#'
 'Ice Cream?' 'cheese fries' 'GRILLED VEGETABLES#?' 'chicken melt'
 'VEGETARIAN PLATTER#' 'side salad?' 'FRUIT SALAD#' 'SIDE SALAD?'
 'Fruit Salad?' 'nachos grande' 'ONION RINGS#' 'NACHOS GRANDE'
 'coca cola#' 'sweet potato fries?' 'MASHED POTATOES#' 'Cheesecake?'
 'CHEESECAKE' 'BROWNIE#?' 'salmon?' 'SIDE SALAD#' 'ORANGE JUICE?'
 'LEMONADE?' 'grilled chicken?' 'chocolate cake#' 'BEEF CHILI#?' 'Salmon?'
 'GARLIC BREAD?' 'SALMON#' 'SWEET POTATO FRIES?' 'ORANGE JUICE#'
 'brownie?' 'GARLIC BREAD#' 'Garlic Bread?' 'pasta alfredo#'
 'pasta alfredo?' 'FRUIT SALAD?' 'brownie#' 'salmon' 'onion rings?'
 'BROWNIE?' 'SWEET POTATO FRIES#' 'CHOCOLATE CAKE#?' 'garlic bread#'
 'orange juice?' 'GRILLED CHICKEN?' 'VEGETARIAN PLATTER?' 'cheese fries#'
 'PASTA ALFREDO#?' 'CHEESECAKE#' 'mashed potatoes?' 'ICE CREAM?' 'water?'
 'MASHED POTATOES#?' 'vegetarian platter#' 'Onion Rings?' 'ONION RINGS'
 'GRILLED VEGETABLES?']
['Digital Wallet' 'Credit Card' 'Cash']

In [ ]:
#javobni shu yerda yozing
import re

df1['category'] = df1['category'].str.lower()
df1['item'] = (df1['item']
    .str.lower()
    .str.replace(r'[#?]', '', regex = True)
    .str.replace(r'\s*\(.*?\)', '', regex=True)
    .str.strip()
)

df1['payment_method'] = df1['payment_method'].str.lower()

In [ ]:
print(df1['category'].unique())
print(df1['item'].unique())
print(df1['payment_method'].unique())

['side dishes' 'main dishes' 'desserts' 'starters' 'drinks']
['mashed potatoes' 'grilled chicken' 'pasta alfredo' 'salmon'
 'garlic bread' 'vegetarian platter' 'brownie' 'sweet potato fries'
 'lemonade' 'side salad' 'orange juice' 'chocolate cake' 'coca cola'
 'grilled vegetables' 'cheese fries' 'beef chili' 'chicken melt'
 'fruit salad' 'french fries' 'ice cream' 'cheesecake' 'iced tea' 'water'
 'nachos grande' 'onion rings' 'steak']
['digital wallet' 'credit card' 'cash']

#7) Maʼlumotlar turini oʻzgartirish.
 * Ustunlarning maʼlumot turlarini tekshiring. Notoʻgʻri turlarga ega boʻlgan ustunlarni toʻgʻri formatga oʻtkazing.
 * `order_date` yoki unga oʻxshash ustunni datetime formatiga oʻtkazing.

In [100]:
#javobni shu yerda yozing
df['order_date'] = pd.to_datetime(df['order_date'])
df.dtypes

order_id                  object
customer_id               object
category                  object
item                      object
price                    float64
quantity                 float64
order_total              float64
order_date        datetime64[ns]
payment_method            object
dtype: object

#8) Mahsulot nomlarida noto‘g‘ri yoki nomaʼlum belgilar (?, NaN, #) mavjudligini tekshiring va ularni tuzating.

In [ ]:
# df['item'].unique()

In [ ]:
#javobni shu yerda yozing
import re

df['item'] = (df['item']
              .str.lower()
              .str.replace(r'[#?]', '', regex = True)
              .str.replace(r'\s*\(.*?\)', '', regex = True)
              )

In [ ]:
df['item'].unique()

array(['side salad', 'mashed potatoes', 'grilled chicken', nan,
       'pasta alfredo', 'salmon', 'garlic bread', 'vegetarian platter',
       'brownie', 'sweet potato fries', 'lemonade', 'orange juice',
       'chocolate cake', 'coca cola', 'grilled vegetables',
       'cheese fries', 'beef chili', 'chicken melt', 'fruit salad',
       'french fries', 'ice cream', 'cheesecake', 'iced tea', 'water',
       'nachos grande', 'onion rings', 'steak'], dtype=object)

#**Maʼlumotlarni filtrlash va qayta ishlash**

#9) Manfiy narx yoki 0 ga teng narx qiymatlarini toping va ularni qanday oʻzgartirish kerakligini hal qiling.

In [ ]:
#javobni shu yerda yozing
df[(df.price < 0) | (df.price == 0)]

df['price'] = df['price'].abs()
df[df['price'] <0].head()

Empty DataFrame
Columns: [order_id, customer_id, category, item, price, quantity, order_total, order_date, payment_method]
Index: []

#10) Boʻsh toifalar (kategoriya) mavjudligini tekshiring va toʻgʻri kategoriya berish strategiyasini ishlab chiqing.

In [74]:
df.category.isnull().sum()

np.int64(36)

In [75]:
df.groupby('category')['price'].mean()

category
Desserts        5.326653
Drinks          2.144582
Main Dishes    14.495485
Side Dishes     3.857431
Starters        5.566107
Name: price, dtype: float64

In [77]:
#javobni shu yerda yozing
def assign_category(price):
  if price <= 3:
    return 'Drinks'
  elif price <=5:
    return 'Side Dishes'
  elif price <= 5.45:
    return 'Desserts'
  elif price <= 10:
    return 'Starter'
  else:
    return 'Main Dishes'

df.loc[df['category'].isnull(), 'category'] = df.loc[df['category'].isnull(), 'price'].apply(assign_category)
df.category.isnull().sum()

np.int64(0)

#11) Bir xil, lekin turlicha yozilgan qiymatlar (Coffee, cofee, COFEE) mavjudligini tekshiring va tuzating.

In [79]:
#javobni shu yerda yozing
print(df['item'].unique())

['side salad' 'mashed potatoes' 'grilled chicken' nan 'pasta alfredo'
 'salmon' 'garlic bread' 'vegetarian platter' 'brownie'
 'sweet potato fries' 'lemonade' 'orange juice' 'chocolate cake'
 'coca cola' 'grilled vegetables' 'cheese fries' 'beef chili'
 'chicken melt' 'fruit salad' 'french fries' 'ice cream' 'cheesecake'
 'iced tea' 'water' 'nachos grande' 'onion rings' 'steak']

#12) `Customer ID` yoki boshqa identifikatorlarning takrorlanishini tekshiring.

In [85]:
#javobni shu yerda yozing
print(df.customer_id.nunique())
print(df.customer_id.value_counts())

100
customer_id
CUST_066    207
CUST_100    200
CUST_055    199
CUST_087    199
CUST_028    198
           ...
CUST_030    153
CUST_045    152
CUST_095    150
CUST_023    147
CUST_060    143
Name: count, Length: 100, dtype: int64

#13) Mahsulotning ortiqcha taʼriflarini olib tashlang (Water (0.5), Water (1.0), Water → faqat Water qoldirish).

In [86]:
#javobni shu yerda yozing
print(df.item.unique())

['side salad' 'mashed potatoes' 'grilled chicken' nan 'pasta alfredo'
 'salmon' 'garlic bread' 'vegetarian platter' 'brownie'
 'sweet potato fries' 'lemonade' 'orange juice' 'chocolate cake'
 'coca cola' 'grilled vegetables' 'cheese fries' 'beef chili'
 'chicken melt' 'fruit salad' 'french fries' 'ice cream' 'cheesecake'
 'iced tea' 'water' 'nachos grande' 'onion rings' 'steak']

#**Qayta ishlangan maʼlumotlar bilan tahlil**

#14) Eng koʻp sotilgan 5 ta mahsulotni aniqlang.

In [95]:
#javobni shu yerda yozing
df['item'].value_counts().head()

item
pasta alfredo    998
side salad       978
water            956
ice cream        936
french fries     897
Name: count, dtype: int64

#15) Har bir mijoz oʻrtacha qancha pul sarflaganini hisoblang.

In [96]:
#javobni shu yerda yozing
df.groupby('customer_id')['order_total'].mean()

customer_id
CUST_001    17.784483
CUST_002    19.904070
CUST_003    17.200637
CUST_004    19.503012
CUST_005    17.918301
              ...
CUST_096    18.752604
CUST_097    19.662983
CUST_098    20.093220
CUST_099    20.920886
CUST_100    18.676020
Name: order_total, Length: 100, dtype: float64

#16) Mijozlarning qaysi kunlarda koʻproq xarid qilgani bo‘yicha tahlil qiling.

In [101]:
#javobni shu yerda yozing
df['order_date'].dt.day_name().value_counts()

order_date
Friday       2531
Monday       2526
Saturday     2525
Thursday     2515
Sunday       2483
Wednesday    2477
Tuesday      2477
Name: count, dtype: int64

#17) Narxi oʻrtacha narxdan ikki barobar yuqori boʻlgan mahsulotlarni toping.

In [104]:
df['price'].mean()

np.float64(6.307231664195278)

In [103]:
#javobni shu yerda yozing
df[df['price'] > df['price'].mean() * 2].head()

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
2,ORD_443849,CUST_029,Main Dishes,grilled chicken,15.0,4.0,60.0,2023-09-27,Credit Card
5,ORD_381680,CUST_031,Main Dishes,salmon,18.0,5.0,90.0,2022-07-20,Digital Wallet
7,ORD_146656,CUST_077,Main Dishes,NaN,15.0,3.0,45.0,2023-02-15,Cash
9,ORD_743636,CUST_085,Main Dishes,vegetarian platter,14.0,5.0,70.0,2022-08-07,NaN
11,ORD_726419,CUST_025,Main Dishes,salmon,18.0,5.0,90.0,2023-10-30,Cash

#18) Mahsulotlar kategoriyalari bo‘yicha tahlil qiling va eng ko‘p sotiladigan kategoriyalarni aniqlang.

In [106]:
#javobni shu yerda yozing
# df.groupby('category')['item'].value_counts()

df.groupby('category')['item'].count().sort_values(ascending=False)

category
Main Dishes    3198
Starters       3196
Desserts       3134
Side Dishes    3130
Drinks         3113
Starter           5
Name: item, dtype: int64

#19) Har bir mijozning oʻrtacha xarid miqdorini (`groupby("customer_id")`) hisoblang.

In [107]:
#javobni shu yerda yozing
df.groupby('customer_id')['quantity'].mean()

customer_id
CUST_001    2.954023
CUST_002    3.116279
CUST_003    2.942675
CUST_004    3.084337
CUST_005    2.928105
              ...
CUST_096    2.973958
CUST_097    3.044199
CUST_098    3.084746
CUST_099    2.962025
CUST_100    2.974490
Name: quantity, Length: 100, dtype: float64

#20) Qanday omillar sotuv hajmiga ta’sir qiladi? Bu bo‘yicha umumiy xulosa chiqaring. Javobni quyida kommentariya sifatida yozing!

In [108]:
#javobni shu yerda yozing

# First and foremost, Price is the primary key to the volume of sales. The majority of people want to buy cheap products.
# Next main indicator is the quality of the item. Everyone wants things that last for a long time and are comfortable to use.
# For some, They want something unique. Their product should be one and only in the world, at least in the neighborhood. This is one of the less caring, yet crucial factors of the rate of sales.